[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED  = "1"
  NODE_VERSION             = "20"
  SECRETS_SCAN_OMIT_KEYS   = "NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SUPABASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"
